server:
  port: 8080

spring:
  application:
    name: user-directory-api

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

# External API Configuration
external:
  api:
    users:
      url: https://dummyjson.com/users
      timeout: 5000
      max-retries: 3

# Resilience4j Configuration
resilience4j:
  retry:
    instances:
      userApiRetry:
        maxAttempts: 3
        waitDuration: 1s
        exponentialBackoffMultiplier: 2

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html